controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_position_controller:
      type: position_controllers/JointGroupPositionController

arm_position_controller:
  ros__parameters:
    joints:
      - dof_base
      - dof_shoulder
      - dof_elbow
      - dof_wrist_pitch
    interface_name: position
