"""기능별 이관 후 자산과 과거 source ledger 이름의 대응. 값·schema는 보존한다."""
from pathlib import Path

PACKAGE = Path(__file__).resolve().parents[1]
PRIVATE_CONFIG = Path.home() / "DAPIER/.local-artifacts/sweepick-field-tools"
SOURCE_PATHS = {'sweepick_261008_concrete_bindings.py': 'integration/sweepick_controller_bindings.py',
 'sweepick_261008_full_episode.py': 'integration/sweepick_manipulation_handoff.py',
 'sweepick_261008_receive_entry.py': 'manipulation/sweepick_right_receive_dispatch.py',
 'sweepick_261008_receive_plan.py': 'manipulation/sweepick_right_receive_planner.py',
 'sweepick_261008_receive_real_adapter.py': 'integration/sweepick_handoff_snapshot_adapter.py',
 'sweepick_261008_receive_runtime.py': 'integration/sweepick_receive_runtime.py',
 'sweepick_261008_receive_session.py': 'integration/sweepick_receive_session.py',
 'sweepick_HARD_GATE_ALLOWLIST.json': 'config/sweepick_HARD_GATE_ALLOWLIST.json',
 'sweepick_PROGRESS_EVIDENCE.json': 'config/sweepick_PROGRESS_EVIDENCE.json',
 'sweepick_bimanual_handover.py': 'manipulation/sweepick_bimanual_handover.py',
 'sweepick_collision_cert.py': 'control/sweepick_collision_preview.py',
 'sweepick_collision_preview.py': 'control/sweepick_collision_preview.py',
 'sweepick_command_application.py': 'control/sweepick_command_application.py',
 'sweepick_commission.py': 'control/sweepick_servo_access.py',
 'sweepick_contact01.py': 'control/sweepick_gripper_contact_inspection.py',
 'sweepick_controller_bindings.py': 'integration/sweepick_controller_bindings.py',
 'sweepick_episode.py': 'recording/sweepick_episode_recorder.py',
 'sweepick_episode_recorder.py': 'recording/sweepick_episode_recorder.py',
 'sweepick_execution_gates.py': 'control/sweepick_execution_gates.py',
 'sweepick_feedback_observation.py': 'perception/sweepick_feedback_observation.py',
 'sweepick_field.py': 'perception/sweepick_observation_capture.py',
 'sweepick_field_r6.py': 'perception/sweepick_feedback_observation.py',
 'sweepick_full_chain.py': 'manipulation/sweepick_bimanual_handover.py',
 'sweepick_gates.py': 'control/sweepick_execution_gates.py',
 'sweepick_grasp.py': 'control/sweepick_gripper_contact_hold.py',
 'sweepick_gripper_contact_hold.py': 'control/sweepick_gripper_contact_hold.py',
 'sweepick_gripper_contact_inspection.py': 'control/sweepick_gripper_contact_inspection.py',
 'sweepick_handoff_snapshot_adapter.py': 'integration/sweepick_handoff_snapshot_adapter.py',
 'sweepick_jaw_profile_left.json': 'config/sweepick_jaw_profile_left.json',
 'sweepick_joint_command_mapping.py': 'control/sweepick_joint_command_mapping.py',
 'sweepick_joint_kinematics.py': 'control/sweepick_joint_kinematics.py',
 'sweepick_kin.py': 'control/sweepick_joint_kinematics.py',
 'sweepick_local_loop.py': 'integration/sweepick_observation_session.py',
 'sweepick_manipulation_handoff.py': 'integration/sweepick_manipulation_handoff.py',
 'sweepick_manipulation_session.py': 'integration/sweepick_manipulation_session.py',
 'sweepick_motion_profile.json': 'config/sweepick_motion_profile.json',
 'sweepick_motion_progress.py': 'control/sweepick_motion_progress.py',
 'sweepick_move_a.py': 'control/sweepick_trajectory_executor.py',
 'sweepick_observation_capture.py': 'perception/sweepick_observation_capture.py',
 'sweepick_observation_session.py': 'integration/sweepick_observation_session.py',
 'sweepick_observation_view.py': 'perception/sweepick_observation_view.py',
 'sweepick_os30a_observation.py': 'perception/sweepick_os30a_observation.py',
 'sweepick_pick01.py': 'integration/sweepick_manipulation_session.py',
 'sweepick_progress.py': 'control/sweepick_motion_progress.py',
 'sweepick_progress_profile.json': 'config/sweepick_progress_profile.json',
 'sweepick_read03_capture.py': 'perception/sweepick_wrist_capture.py',
 'sweepick_real_command.py': 'control/sweepick_joint_command_mapping.py',
 'sweepick_real_exec.py': 'control/sweepick_command_application.py',
 'sweepick_real_rig.py': 'integration/sweepick_replay_rig.py',
 'sweepick_receive_runtime.py': 'integration/sweepick_receive_runtime.py',
 'sweepick_receive_session.py': 'integration/sweepick_receive_session.py',
 'sweepick_replay_rig.py': 'integration/sweepick_replay_rig.py',
 'sweepick_right_receive_dispatch.py': 'manipulation/sweepick_right_receive_dispatch.py',
 'sweepick_right_receive_planner.py': 'manipulation/sweepick_right_receive_planner.py',
 'sweepick_sdk_top.py': 'perception/sweepick_os30a_observation.py',
 'sweepick_servo_access.py': 'control/sweepick_servo_access.py',
 'sweepick_trajectory.py': 'control/sweepick_trajectory_profile.py',
 'sweepick_trajectory_executor.py': 'control/sweepick_trajectory_executor.py',
 'sweepick_trajectory_profile.py': 'control/sweepick_trajectory_profile.py',
 'sweepick_view.py': 'perception/sweepick_observation_view.py',
 'sweepick_wrist_capture.py': 'perception/sweepick_wrist_capture.py'}
RECEIVE_MODULES = {'concrete_bindings': 'sweepick.integration.sweepick_controller_bindings',
 'full_episode': 'sweepick.integration.sweepick_manipulation_handoff',
 'receive_entry': 'sweepick.manipulation.sweepick_right_receive_dispatch',
 'receive_plan': 'sweepick.manipulation.sweepick_right_receive_planner',
 'receive_real_adapter': 'sweepick.integration.sweepick_handoff_snapshot_adapter',
 'receive_runtime': 'sweepick.integration.sweepick_receive_runtime',
 'receive_session': 'sweepick.integration.sweepick_receive_session'}
FIELD_MODULES = {'collision_cert': 'sweepick.control.sweepick_collision_preview',
 'commission': 'sweepick.control.sweepick_servo_access',
 'contact01': 'sweepick.control.sweepick_gripper_contact_inspection',
 'episode': 'sweepick.recording.sweepick_episode_recorder',
 'field': 'sweepick.perception.sweepick_observation_capture',
 'field_r6': 'sweepick.perception.sweepick_feedback_observation',
 'full_chain': 'sweepick.manipulation.sweepick_bimanual_handover',
 'gates': 'sweepick.control.sweepick_execution_gates',
 'grasp': 'sweepick.control.sweepick_gripper_contact_hold',
 'kin': 'sweepick.control.sweepick_joint_kinematics',
 'local_loop': 'sweepick.integration.sweepick_observation_session',
 'move_a': 'sweepick.control.sweepick_trajectory_executor',
 'pick01': 'sweepick.integration.sweepick_manipulation_session',
 'progress': 'sweepick.control.sweepick_motion_progress',
 'read03_capture': 'sweepick.perception.sweepick_wrist_capture',
 'real_command': 'sweepick.control.sweepick_joint_command_mapping',
 'real_exec': 'sweepick.control.sweepick_command_application',
 'real_rig': 'sweepick.integration.sweepick_replay_rig',
 'sdk_top': 'sweepick.perception.sweepick_os30a_observation',
 'trajectory': 'sweepick.control.sweepick_trajectory_profile',
 'view': 'sweepick.perception.sweepick_observation_view'}

def source_path(name):
    return PACKAGE / SOURCE_PATHS[name] if name in SOURCE_PATHS else PRIVATE_CONFIG / name

def source_files():
    return sorted({source_path(name) for name in SOURCE_PATHS if name.endswith(".py") or "profile" in name})
